<H1>Slicing matrices</H1>

In [1]:
import numpy as np
from inet import utils

In [2]:
nPV = 2 
matrix = np.loadtxt('../data/2_170411_01.syn', dtype=int)# load an example matrix
ncells = matrix.shape[0]
matrix

array([[0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

<H2>Select only reciprocal inhibition (II) </H2>
Reciprocal connections are bidirectional connections between PV interneurons

In [3]:
matrix[:2][:,(0,1)] # II = matrix[ :nPV][ :,range(nPV)]

array([[0, 1],
       [0, 0]])

In [4]:
utils.II_slice(matrix,2)

array([[0, 1],
       [0, 0]])

<H2>Select connections from inhibitory to excitatory neurons (IE)</H2>

In [5]:
utils.IE_slice(matrix,2)

array([[0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1]])

In [6]:
matrix[:2][:,(2,3,4,5,6)] # IE = matrix[ :nPV][ :,range(nPV,ncells)]

array([[0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1]])

<H2>Select connections from excitatory to inhibitory neurons (EI)</H2>

In [7]:
utils.EI_slice(matrix,2)

array([[0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0]])

In [8]:
matrix[2:][:,(0,1)] # EI = matrix[nPV:][,:range(nPV)]

array([[0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0]])