<H1>Motifs in matrices</H1>

In [1]:
# preliminary loading
%pylab inline


Populating the interactive namespace from numpy and matplotlib


In [2]:
nPV = 2 
matrix = np.loadtxt('../data/2_170411_01.syn', dtype=int)# load an example matrix
ncells = matrix.shape[0]
matrix

array([[0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

Select connections from Inhibitory neurons (II and IE)

In [3]:
# Slice from inhibitory cells matrix[:nPV]
matrix[0:2]

array([[0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 1]])

In [4]:
matrix[:2][:,(0,1)] # II = matrix[ :nPV][ :,range(nPV)]

array([[0, 1],
       [0, 0]])

In [42]:
matrix[:2][:,(2,3,4,5,6)] # IE = matrix[ :nPV][ :,range(nPV,ncells)]

array([[0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1]])

Select connections from excitatory neurons EI

In [6]:
# Slice from excitatory cells matrix[nPV:]
matrix[2:]

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])

In [7]:
matrix[2:][:,(0,1)] # EI = matrix[nPV:][,:range(nPV)]

array([[0, 0],
       [0, 0],
       [0, 1],
       [0, 0],
       [0, 0]])

count number synapses of IE neurons


In [46]:
EI = matrix[:2][:,range(nPV,ncells)]
EI

array([[0, 0, 1, 0, 0],
       [1, 0, 0, 0, 1]])

In [59]:
np.where(EI==0)

(array([0, 0, 0, 0, 1, 1, 1]), array([0, 1, 3, 4, 1, 2, 3]))

In [60]:
EI[np.where(EI==0)]

array([0, 0, 0, 0, 0, 0, 0])

In [54]:
ids = np.nonzero(EI) #
print(ids)

(array([0, 1, 1]), array([2, 0, 4]))


In [53]:
EI[ids]

array([1, 1, 1])

In [49]:

chem_syn = EI[EI==1].size # chemical synapse
elec_syn = EI[EI==2].size # electrical synapse
both_syn = EI[EI==3].size # both

print(chem_syn, elec_syn, both_syn)

(3, 0, 0)
